name: beesweeper # you probably want to 'snapcraft register <name>'
title: Beesweeper
base: core20 # the base snap is the execution environment for this snap
version: '0.12' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hex and Classic Minesweeper all in one. # 79 char long summary
description: |
  Hex and classic implementation of the game. Supports various options
  including flags and chording. Plus has a new auto-flag feature.
  Play on three levels of difficulty and custom field sizes.

#  BeeSweeper is hex minesweeper, a game that hardly needs an introduction. 
#  Uncover all mines as quickly as you can to win the game. Play on three 
#  difficulty levels and on various field sizes. All features of the classic 
#  game and more are supported. A version of this game has been published 
#  also for iOS and BlackBerry phones in early 2010s.

license: MIT

contact: intheswim@gmail.com

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: snap/gui/icon.png

donation: https://www.paypal.com/donate/?hosted_button_id=8EF7Z8LBJDT2S

# layout:
#  /usr/local/bin:
#    bind: $SNAP/usr/local/bin

parts:

  game-assets:
    source: .
    plugin: dump
    stage: 
      - assets
      - images
      - sounds

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  beesweeper:
    after:
      - desktop-glib-only
    plugin: make
    source: .
    build-packages:
      - g++
      - make
      - libboost-program-options-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
#      - libgl1-mesa-dri
#      - libglu1-mesa
#      - libgl1-mesa-glx
      - libpulse0
      - libasound2
      - libboost-program-options1.71.0

apps:
  beesweeper:
    command: usr/local/bin/mines
    command-chain: ["bin/desktop-launch"]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
#      - opengl
      - pulseaudio
      - audio-playback
      - alsa    
